server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 9060
#eureka:
#  instance:
#    lease-renewal-interval-in-seconds: 5 #定义服务续约任务的调用间隔时间，默认为30秒
#    lease-expiration-duration-in-seconds: 10 #定义服务失效的时间，默认为90秒
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    registry-fetch-interval-seconds: 10 #间隔多久拉取服务注册信息，默认为30秒
#    service-url:
#      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
ribbon:
  http:
    client:
      enabled: false
  okhttp:
    enabled: true
  #com.netflix.loadbalancer.RandomRule #配置规则 随机
  #com.netflix.loadbalancer.RoundRobinRule #配置规则 轮询
  #com.netflix.loadbalancer.RetryRule #配置规则 重试
  #com.netflix.loadbalancer.WeightedResponseTimeRule #配置规则 响应时间权重
  #com.netflix.loadbalancer.BestAvailableRule #配置规则 最空闲连接策略
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #配置规则 轮询
  ConnectTimeout: 3000 #请求连接超时时间，默认2000ms
  ReadTimeout: 30000 #请求处理的超时时间，默认5000ms
  OkToRetryOnAllOperations: false #对所有请求都进行重试，默认只重试GET请求
  MaxAutoRetriesNextServer: 1 #切换实例的重试次数,默认1
  MaxAutoRetries: 0 #对当前实例的重试次数，默认0
  eager-load:
    enabled: true #开启饥饿加载 解决第一次feign调用失败的问题
    clients: mall-member
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
      isolation:
        thread:
          #断路器超时时间，默认1000ms
          timeoutInMilliseconds: 60000
feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  #开启请求与响应的压缩
  compression:
    request:
      enabled: true
    response:
      enabled: true
spring:
  jackson:
    time-zone: GMT+8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      default:
        url: jdbc:mysql://localhost:3306/jbos?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL
        username: jbos
        password: jbos
      camunda:
        url: jdbc:mysql://localhost:3306/camunda?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL
        username: camunda
        password: 123456
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
      #使用非公平锁
      useUnfairLock: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: false
      validationQueryTimeout: 1
      keepAlive: true
#mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.mall.member.domain.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断",2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    # Sequence序列接口实现类配置
    #key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #逻辑删除配置
    logic-delete-value: 1
    logic-not-delete-value: 0
    #自定义SQL注入器
    #sql-injector: com.baomidou.mybatisplus.extension.injector.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl