server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8060
spring:
  jwt:
    secret: 123456  #密钥
    expireTime: 1   #过期时间，默认60分钟
##eureka:
##  instance:
##    lease-renewal-interval-in-seconds: 5 #定义服务续约任务的调用间隔时间，默认为30秒
##    lease-expiration-duration-in-seconds: 10 #定义服务失效的时间，默认为90秒
##    prefer-ip-address: true
##  client:
##    fetch-registry: true
##    register-with-eureka: true
##    registry-fetch-interval-seconds: 5 #获取注册信息的时间间隔（s），默认为30秒
##    service-url:
##      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
#
zuul:
  add-host-header: false
  routes:
    mall-redis:
      path: /api/redis/**
      serviceId: mall-redis
    mall-auth:
      path: /api/auth/**
      serviceId: mall-auth
    maill-admin:
      path: /api/admin/**
      serviceId: mall-admin
    mall-workflow:
      path: /api/workflow/**
      serviceId: mall-workflow
    mall-member:
      path: /api/member/**
      serviceId: mall-member
    mall-product:
      path: /api/product/**
      serviceId: mall-product
    mall-order:
      path: /api/order/**
      serviceId: mall-order
    mall-pay:
      path: /api/pay/**
      serviceId: mall-pay
  filter:
    excludeUri: /**/login,/**/logout,/**/captcha,/**/registry

ribbon:
  http:
    client:
      enabled: false
  okhttp:
    enabled: true

  #com.netflix.loadbalancer.RandomRule #配置规则 随机
  #com.netflix.loadbalancer.RoundRobinRule #配置规则 轮询
  #com.netflix.loadbalancer.RetryRule #配置规则 重试
  #com.netflix.loadbalancer.WeightedResponseTimeRule #配置规则 响应时间权重
  #com.netflix.loadbalancer.BestAvailableRule #配置规则 最空闲连接策略
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #配置规则 轮询
  ConnectTimeout: 3000 #请求连接超时时间，默认2000
  ReadTimeout: 30000 #请求处理的超时时间，默认5000
  OkToRetryOnAllOperations: true #对所有请求都进行重试
  MaxAutoRetriesNextServer: 1 #切换实例的重试次数,默认1
  MaxAutoRetries: 0 #对当前实例的重试次数，默认0

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
      isolation:
        thread:
          #断路器超时时间，默认1000ms
          timeoutInMilliseconds: 60000


