spring:
  security:
    filter:
      loginUri: /**/login
      logoutUri: /**/logout
      excludeUri: /**/captcha,/**/demo/**,/**/doc.html,/**/swagger-ui.html,/**/webjars/**,/**/swagger-resources/**,/**/v2/**,/**/engine-rest/**

  jwt:
    secret: 123456  #密钥
    expireTime: 720   #过期时间，默认60分钟
  redis:
    enable: false
    database: 0
    host: 127.0.0.1
    port: 6379
    password:      # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    lettuce:  #不是jedis, springboot2.0以上默认是lettuce
      pool:
        max-active: 1000  # 最大连接数（使用负值表示没有限制）
        max-wait: -1ms    # 最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 最大空闲连接
        min-idle: 5       # 最小空闲连接
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      default:
        url: jdbc:mysql://localhost:3306/jbos?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL&socketTimeout=60000
        username: jbos
        password: ENC(z/dPUd+V2Exjh/dKtt/KFQ==)
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
      #使用非公平锁
      useUnfairLock: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: false
      validationQueryTimeout: 1
      keepAlive: true
#mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.mall.gateway.domain.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断",2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    # Sequence序列接口实现类配置
    #key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #逻辑删除配置
    logic-delete-value: 1
    logic-not-delete-value: 0
    #自定义SQL注入器
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
zuul:
  add-host-header: false
  routes:
    #本地路由配置
    mall-auth:
      path: /api/auth/**
      url: forward:/auth
    #远程路由配置
    mall-redis:
      path: /api/redis/**
      serviceId: mall-redis
    mall-admin:
      path: /api/admin/**
      serviceId: mall-admin
    mall-workflow:
      path: /api/workflow/**
      serviceId: mall-workflow
    mall-product:
      path: /api/business/**
      serviceId: mall-business
  filter:
    excludeUri: /**/login,/**/logout,/**/captcha,/**/registry,/**/error/,/**/swagger-ui.html,/**/webjars/**,/**/swagger-resources/**,/**/v2/**,/**/engine-rest/**

ribbon:
  http:
    client:
      enabled: false
  okhttp:
    enabled: true

  #com.netflix.loadbalancer.RandomRule #配置规则 随机
  #com.netflix.loadbalancer.RoundRobinRule #配置规则 轮询
  #com.netflix.loadbalancer.RetryRule #配置规则 重试
  #com.netflix.loadbalancer.WeightedResponseTimeRule #配置规则 响应时间权重
  #com.netflix.loadbalancer.BestAvailableRule #配置规则 最空闲连接策略
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #配置规则 轮询
  ConnectTimeout: 3000 #请求连接超时时间，默认2000
  ReadTimeout: 30000 #请求处理的超时时间，默认5000
  OkToRetryOnAllOperations: true #对所有请求都进行重试
  MaxAutoRetriesNextServer: 1 #切换实例的重试次数,默认1
  MaxAutoRetries: 0 #对当前实例的重试次数，默认0

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
      isolation:
        thread:
          #断路器超时时间，默认1000ms
          timeoutInMilliseconds: 60000


