##eureka:
##  instance:
##    lease-renewal-interval-in-seconds: 5 #定义服务续约任务的调用间隔时间，默认为30秒
##    lease-expiration-duration-in-seconds: 10 #定义服务失效的时间，默认为90秒
##    prefer-ip-address: true
##  client:
##    fetch-registry: true
##    register-with-eureka: true
##    registry-fetch-interval-seconds: 5 #获取注册信息的时间间隔（s），默认为30秒
##    service-url:
##      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
#
zuul:
  add-host-header: false
  routes:
    mall-redis:
      path: /api/redis/**
      serviceId: mall-redis
    mall-auth:
      path: /api/auth/**
      serviceId: mall-auth
    maill-admin:
      path: /api/admin/**
      serviceId: mall-admin
    mall-workflow:
      path: /api/workflow/**
      serviceId: mall-workflow
    mall-member:
      path: /api/member/**
      serviceId: mall-member
    mall-product:
      path: /api/product/**
      serviceId: mall-product
    mall-order:
      path: /api/order/**
      serviceId: mall-order
    mall-pay:
      path: /api/pay/**
      serviceId: mall-pay
  filter:
    excludeUri: /**/login,/**/logout,/**/captcha,/**/registry

ribbon:
  http:
    client:
      enabled: false
  okhttp:
    enabled: true

  #com.netflix.loadbalancer.RandomRule #配置规则 随机
  #com.netflix.loadbalancer.RoundRobinRule #配置规则 轮询
  #com.netflix.loadbalancer.RetryRule #配置规则 重试
  #com.netflix.loadbalancer.WeightedResponseTimeRule #配置规则 响应时间权重
  #com.netflix.loadbalancer.BestAvailableRule #配置规则 最空闲连接策略
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #配置规则 轮询
  ConnectTimeout: 3000 #请求连接超时时间，默认2000
  ReadTimeout: 30000 #请求处理的超时时间，默认5000
  OkToRetryOnAllOperations: true #对所有请求都进行重试
  MaxAutoRetriesNextServer: 1 #切换实例的重试次数,默认1
  MaxAutoRetries: 0 #对当前实例的重试次数，默认0

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
      isolation:
        thread:
          #断路器超时时间，默认1000ms
          timeoutInMilliseconds: 60000
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #driverClassName: com.mysql.jdbc.Driver
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      default:
        url: jdbc:mysql://127.0.0.1:3306/jbos?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
        username: jbos
        password: jbos
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
      #使用非公平锁
      useUnfairLock: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: false
      validationQueryTimeout: 1
      keepAlive: true
#mybatis
mybatis:
  mapperLocations: classpath*:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.mall.gateway.domain.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断",2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    # Sequence序列接口实现类配置
    #key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #逻辑删除配置
    logic-delete-value: 1
    logic-not-delete-value: 0
    #自定义SQL注入器
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true

