spring:
  security:
    filter:
      loginUri: /*/*/login
      logoutUri: /*/*/logout
      excludeUri: /*/*/login,/*/*/logout,/captcha,/demo/*,/doc.html,/*/swagger-ui.html,/*/webjars/*,/*/swagger-resources/*,/*/v2/*,/*/engine-rest/*
  jwt:
    secret: 123456  #密钥
    expireTime: 600   #过期时间，默认60分钟
  redis:
    enable: false
    database: 0
    host: 127.0.0.1
    port: 6379
    password:      # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    lettuce: #不是jedis, springboot2.0以上默认是lettuce
      pool:
        max-active: 1000  # 最大连接数（使用负值表示没有限制）
        max-wait: -1ms    # 最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 最大空闲连接
        min-idle: 5       # 最小空闲连接
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      default:
        url: jdbc:mysql://127.0.0.1:3306/jbos?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL&socketTimeout=60000
        username: jbos
        password: jbos
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
      #使用非公平锁
      useUnfairLock: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: false
      validationQueryTimeout: 1
      keepAlive: true
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowedOriginPatterns: "*"
            allowedMethods: "GET, POST, PUT, DELETE, OPTIONS"
            allowedHeaders: "*"
        add-to-simple-url-handler-mapping: true
      excludeUri: /**/login,/**/logout,/**/captcha,/**/registry
      default-filters:
        - name: CircuitBreaker
          args:
            name: fallbackcmd
            fallbackUri: forward:/fallback
      routes:
        #本地路由配置
        - id: mall-auth
          uri: http://127.0.0.1:8060/
          predicates:
            - Path=/api/auth/**
        #远程路由配置
        - id: mall-admin
          uri: lb://mall-admin
          predicates:
            - Path=/api/admin/**
          filters:
            - StripPrefix=2
        - id: mall-member
          uri: lb://mall-member
          predicates:
            - Path=/api/member/**
          filters:
            - StripPrefix=2
        - id: mall-business
          uri: lb://mall-business
          predicates:
            - Path=/api/business/**
          filters:
            - StripPrefix=2
feign:
  httpclient:
    enabled: true
  okhttp:
    enabled: true

ribbon:
  #com.netflix.loadbalancer.RandomRule #配置规则 随机
  #com.netflix.loadbalancer.RoundRobinRule #配置规则 轮询
  #com.netflix.loadbalancer.RetryRule #配置规则 重试
  #com.netflix.loadbalancer.WeightedResponseTimeRule #配置规则 响应时间权重
  #com.netflix.loadbalancer.BestAvailableRule #配置规则 最空闲连接策略
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #配置规则 轮询
  ConnectTimeout: 3000 #请求连接超时时间，默认2000
  ReadTimeout: 30000 #请求处理的超时时间，默认5000
  OkToRetryOnAllOperations: true #对所有请求都进行重试
  MaxAutoRetriesNextServer: 1 #切换实例的重试次数,默认1
  MaxAutoRetries: 0 #对当前实例的重试次数，默认0
#mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml