spring:
  application:
    name: mall-eurekaserver
  profiles:
    active: peer1
#actuator 端点信息配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
---
spring:
  profiles: peer1
  boot:
    admin:
      client:
        url: http://127.0.0.1:9528/
---
spring:
  profiles: peer2
---