server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8070
spring:
  application:
    name: mall-auth
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    loadbalancer:
      retry:
        enabled: true
  security:
    filter:
      loginUri: /login
      excludeUri: /captcha,/demo/**
  jwt:
    secret: 123456  #密钥
    expireTime: 12   #过期时间，默认24小时
