server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8080
spring:
  application:
    name: mall-admin
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
  mvc:
    servlet:
      load-on-startup: 0   # 启动时立即初始化 dispatcherServlet，数值表示延迟多久进行自动初始化dispatcherServlet，0是立即初始化
  boot:
    admin:
      client:
        url: http://127.0.0.1:9528/
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

