server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8080
spring:
  application:
    name: mall-admin
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
  mvc:
    servlet:
      load-on-startup: 0   # 启动时立即初始化 dispatcherServlet，数值表示延迟多久进行自动初始化dispatcherServlet，0是立即初始化
  boot:
    admin:
      client:
        url: http://127.0.0.1:9528/
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
ribbon:
  http:
    client:
      enabled: false
  okhttp:
    enabled: true
  #com.netflix.loadbalancer.RandomRule #配置规则 随机
  #com.netflix.loadbalancer.RoundRobinRule #配置规则 轮询
  #com.netflix.loadbalancer.RetryRule #配置规则 重试
  #com.netflix.loadbalancer.WeightedResponseTimeRule #配置规则 响应时间权重
  #com.netflix.loadbalancer.BestAvailableRule #配置规则 最空闲连接策略
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #配置规则 轮询
  ConnectTimeout: 3000 #请求连接超时时间，默认2000ms
  ReadTimeout: 30000 #请求处理的超时时间，默认5000ms
  OkToRetryOnAllOperations: false #对所有请求都进行重试，默认只重试GET请求
  MaxAutoRetriesNextServer: 1 #切换实例的重试次数,默认1
  MaxAutoRetries: 0 #对当前实例的重试次数，默认0
  eager-load:
    enabled: true #开启饥饿加载 解决第一次feign调用失败的问题
    clients: mall-admin
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
      isolation:
        thread:
          #断路器超时时间，默认1000ms
          timeoutInMilliseconds: 60000
feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  #开启请求与响应的压缩
  compression:
    request:
      enabled: true
    response:
      enabled: true
