server:
  port: 8090
spring:
  application:
    name: mall-workflow
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5 #定义服务续约任务的调用间隔时间，默认为30秒
    lease-expiration-duration-in-seconds: 10 #定义服务失效的时间，默认为90秒
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 10 #间隔多久拉取服务注册信息，默认为30秒
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
ribbon:
  http:
    client:
      enabled: false
  okhttp:
    enabled: true
  #com.netflix.loadbalancer.RandomRule #配置规则 随机
  #com.netflix.loadbalancer.RoundRobinRule #配置规则 轮询
  #com.netflix.loadbalancer.RetryRule #配置规则 重试
  #com.netflix.loadbalancer.WeightedResponseTimeRule #配置规则 响应时间权重
  #com.netflix.loadbalancer.BestAvailableRule #配置规则 最空闲连接策略
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #配置规则 轮询
  ConnectTimeout: 1000 #请求连接超时时间
  ReadTimeout: 2000 #请求处理的超时时间
  OkToRetryOnAllOperations: true #对所有请求都进行重试
  MaxAutoRetriesNextServer: 2 #切换实例的重试次数
  MaxAutoRetries: 1 #对当前实例的重试次数
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
      isolation:
        thread:
          timeoutInMilliseconds: 5000
feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  #开启请求与响应的压缩
  compression:
    request:
      enabled: true
    response:
      enabled: true
camunda:
  bpm:
     #配置账户密码来访问Camunda自带的管理界面
    admin-user:
       id: admin
       password: admin
       first-name: admin
    filter:
       create: All tasks
    deployment-resource-pattern: classpath*:processes/*.bpmn
logging:
  level:
    com.mall.*: debug
