server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 9070
spring:
  application:
    name: mall-product
  servlet:
    multipart:
      max-file-size: 32MB #文件最大值，默认10MB
      max-request-size: 512MB #文件总的最大值，默认10MB
    upload:
      repo: /nas/upload #文件存储位置
    imageio:
      endpoint-url: http://127.0.0.1/mall/image
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    default-property-inclusion: non_null
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

