server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 9080
spring:
  redis:
    enable: false
    database: 0
    host: 127.0.0.1
    port: 6379
    password:      # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    lettuce:  #不是jedis, springboot2.0以上默认是lettuce
      pool:
        max-active: 1000  # 最大连接数（使用负值表示没有限制）
        max-wait: -1ms    # 最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 最大空闲连接
        min-idle: 5       # 最小空闲连接
  data:
    elasticsearch:
      cluster-name: jbos-mall
      cluster-nodes: 127.0.0.1:9300,127.0.0.1:9301
