server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 9070
spring:
  application:
    name: mall-business
  profiles:
    active: dev
#actuator 端点信息配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
---
spring:
  profiles: dev
  boot:
    admin:
      client:
        url: http://127.0.0.1:9528/
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  # 配置 nacos 的服务地址
        group: dev  # 配置组，默认就是 DEFAULT_GROUP
      config:
        server-addr: 127.0.0.1:8848  # 配置 nacos 的服务地址
        file-extension: yml  # 加载 dataid 配置文件的后缀，默认是 properties
        group: dev  # 配置组，默认就是 DEFAULT_GROUP
#eureka:
#  instance:
#    lease-renewal-interval-in-seconds: 5 #定义服务续约任务的调用间隔时间，默认为30秒
#    lease-expiration-duration-in-seconds: 10 #定义服务失效的时间，默认为90秒
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    registry-fetch-interval-seconds: 10 #间隔多久拉取服务注册信息，默认为30秒
#    service-url:
#      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
---
spring:
  profiles: sit
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8849  # 配置 nacos 的服务地址
        group: sit  # 配置组，默认就是 DEFAULT_GROUP
      config:
        server-addr: 127.0.0.1:8849  # 配置 nacos 的服务地址
        file-extension: yml  # 加载 dataid 配置文件的后缀，默认是 properties
        group: sit  # 配置组，默认就是 DEFAULT_GROUP
---
