server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 9080
spring:
  application:
    name: mall-redis
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    loadbalancer:
      retry:
        enabled: true
#eureka:
#  instance:
#    lease-renewal-interval-in-seconds: 5 #定义服务续约任务的调用间隔时间，默认为30秒
#    lease-expiration-duration-in-seconds: 10 #定义服务失效的时间，默认为90秒
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    registry-fetch-interval-seconds: 5 #获取注册信息的时间间隔（s），默认为30秒
#    service-url:
#      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/